# Generated by Django 4.0.5 on 2022-06-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Pic',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
